# Notebook to compute the LRS slit corner, V3IDLYANGLE, and midpoint locations in v2,v3 for the SIAF

The LRS slit midpoint and corners are defined in pixel coordinates, but implemented in the SIAF in v2/v3 coordinates as a SLIT type object.  Likewise, the LRS slit is the only Imager detector aperture whose V3IDLYANGLE is set directly at the aperture instead of sharing a single angle for the entire detector.  This notebook must be rerun to compute the SIAF inputs whenever the Imager distortion solution changes.

In [1]:
import os as os
import numpy as np
from numpy.testing import assert_allclose
import pdb as pdb
import miricoord.imager.mirim_tools as mt

In [2]:
mt.set_toolversion('lre5')
mt.version()

'lre5'

In [3]:
xref,yref=326.13-1,300.70-1 # Convert from SIAF to 0-indexed
v2ref,v3ref=mt.xytov2v3(xref,yref,'F770W')
v2ref,v3ref

(array([-414.65983587]), array([-400.60455047]))

In [4]:
# V3IDLYANGLE
v3idlyangle=mt.v3imarot(xref,yref)[0]
v3idlyangle

array([4.75201141])

In [5]:
# Lower-left corner
xll,yll=304.77-1, 298.38-1
v2ll,v3ll=mt.xytov2v3(xll,yll,'F770W')
v2ll,v3ll

(array([-412.32681378]), array([-401.05586746]))

In [6]:
# Lower-right corner
xlr,ylr=347.49-1, 298.38-1
v2lr,v3lr=mt.xytov2v3(xlr,ylr,'F770W')
v2lr,v3lr

(array([-417.03539523]), array([-400.66510766]))

In [7]:
# Upper-right corner
xur,yur=347.49-1, 303.03-1
v2ur,v3ur=mt.xytov2v3(xur,yur,'F770W')
v2ur,v3ur

(array([-416.99267929]), array([-400.15212251]))

In [8]:
# Upper-left corner
xul,yul=304.77-1, 303.03-1
v2ul,v3ul=mt.xytov2v3(xul,yul,'F770W')
v2ul,v3ul

(array([-412.28425894]), array([-400.54307374]))

In [9]:
# Print the result in the format required by SIAF input
print("{:>21} ,{:>10} ,{:>12} ,{:>11} ,{:>9} ,{:>9} ,{:>10} ,{:>10} ,{:>8} ,{:>8} ,{:>8} ,\
{:>8} ,{:>17} ,{:>16} ,{:>12} ,{:>10} ,{:>10} ,{:>10} ,{:>10} ,{:>10} ,{:>10} ,{:>10} ,{:>10} ,\
{:>10} ,{:>10} ,{:>10}".format('AperName','AperType','V3IdlYAngle','VIdlParity','XDetRef','YDetRef',\
                               'XSciSize','YSciSize','XCorner','YCorner','XSciRef','YSciRef',\
                               'parent_apertures','dependency_type','SliceName','SliceNum','v2ref','v3ref',\
                               'v2ll','v2ul','v2ur','v2lr','v3ll','v3ul','v3ur','v3lr'))

print("{val1:>21} ,{val2:>10} ,{0:>12.6f} ,{val4:>11} ,{val5:>9} ,{val5:>9} ,{val5:>10} ,{val5:>10} ,\
{val5:>8} ,{val5:>8} ,{val5:>8} ,{val5:>8} ,{val5:>17} ,{val5:>16} ,{val5:>12} ,{val5:>10} ,{1:>10.3f} ,\
{2:>10.3f} ,{3:>10.3f} ,{4:>10.3f} ,{5:>10.3f} ,{6:>10.3f} ,{7:>10.3f} ,{8:>10.3f} ,{9:>10.3f} ,\
{10:>10.3f}".format(v3idlyangle[0],v2ref[0],v3ref[0],v2ll[0],v2ul[0],v2ur[0],v2lr[0],v3ll[0],v3ul[0],\
                    v3ur[0],v3lr[0],val1='MIRIM_SLIT',val2='SLIT',val4='-1',val5='None'))

             AperName ,  AperType , V3IdlYAngle , VIdlParity ,  XDetRef ,  YDetRef ,  XSciSize ,  YSciSize , XCorner , YCorner , XSciRef , YSciRef , parent_apertures , dependency_type ,   SliceName ,  SliceNum ,     v2ref ,     v3ref ,      v2ll ,      v2ul ,      v2ur ,      v2lr ,      v3ll ,      v3ul ,      v3ur ,      v3lr
           MIRIM_SLIT ,      SLIT ,    4.752011 ,         -1 ,     None ,     None ,      None ,      None ,    None ,    None ,    None ,    None ,             None ,            None ,        None ,      None ,  -414.660 ,  -400.605 ,  -412.327 ,  -412.284 ,  -416.993 ,  -417.035 ,  -401.056 ,  -400.543 ,  -400.152 ,  -400.665


Compute the LRS slitless location for good measure (though we don't need to insert that by hand to the SIAF)

In [10]:
x,y=38.5-1,829.0-1
v2,v3=mt.xytov2v3(x,y,'F770W')
v2,v3

(array([-378.39245074]), array([-344.9851225]))