# Notebook to compute the LRS slit corner and midpoint locations in v2,v3 for the SIAF

In [1]:
import os as os
import numpy as np
from numpy.testing import assert_allclose
import pdb as pdb
import miricoord.miricoord.imager.mirim_tools as mt
mt.set_toolversion('cdp7')
mt.version()

'cdp7'

In [2]:
xmid,ymid=326.13-1,300.70-1 # Convert from SIAF to 0-indexed
v2,v3=mt.xytov2v3(xmid,ymid,'F770W')
v2,v3

(array([-415.06904661]), array([-400.5759204]))

In [3]:
# Lower-left corner
x,y=304.77-1, 298.38-1
v2,v3=mt.xytov2v3(x,y,'F770W')
v2,v3

(array([-412.73515523]), array([-401.0277591]))

In [4]:
# Lower-right corner
x,y=347.49-1, 298.38-1
v2,v3=mt.xytov2v3(x,y,'F770W')
v2,v3

(array([-417.4453235]), array([-400.63635533]))

In [5]:
# Upper-right corner
x,y=347.49-1, 303.03-1
v2,v3=mt.xytov2v3(x,y,'F770W')
v2,v3

(array([-417.40292481]), array([-400.12314081]))

In [6]:
# Upper-left corner
x,y=304.77-1, 303.03-1
v2,v3=mt.xytov2v3(x,y,'F770W')
v2,v3

(array([-412.69299168]), array([-400.51473621]))

And the LRS slitless location for good measure

In [7]:
x,y=38.5-1,829.0-1
v2,v3=mt.xytov2v3(x,y,'F770W')
v2,v3

(array([-378.83207368]), array([-344.94454331]))