## Test the MIRI MRS distortion solution (standalone and JWST pipeline versions) ##

### First import the things that we need from the pipeline code ###

In [1]:
import os as os
import numpy as np
from numpy.testing import utils
from numpy.testing import assert_allclose
import pdb as pdb


/var/folders/lg/jw_brb093bl9n39fbgn1cw080001fw/T/ipykernel_34045/1106886355.py:3: DeprecationWarning: Importing from numpy.testing.utils is deprecated since 1.15.0, import from numpy.testing instead.
  from numpy.testing import utils


Import the MIRI coordinates code from https://github.com/STScI-MIRI/miricoord and ensure that it is on the PYTHONPATH.  Also ensure that the local data directory environmental variable is set:

setenv MIRICOORD_DATA_DIR /YourLocalPathToData/ (this is where io will happen)

In [2]:
data_dir=os.path.expandvars('$MIRICOORD_DATA_DIR')

### First we'll look at the standalone distortion solution (mrs_tools) ###

In [3]:
import miricoord.mrs.mrs_tools as mrst
mrst.set_toolversion('flt4')

Define a point on the MRS (0-indexed convention) and convert to v2,v3 for Ch1A

In [4]:
x=[194.0,231.0]
y=[512.0,700.0]
band='4C'

Convert this pixel location to the MRS local alpha,beta,lam coordinates

In [5]:

values=mrst.xytoabl(x,y,band)
v2,v3=mrst.abtov2v3(values['alpha'],values['beta'],band)

The returned values are a dictionary of different entries, including input pixels, output alpha/beta coordinates, wavelength (lam), and slice number/name.

In [6]:
values,v2,v3

({'x': array([194., 231.]),
  'y': array([512., 700.]),
  'alpha': array([-0.08228878, -0.0200367 ]),
  'beta': array([ 2.29611932, -1.64008523]),
  'lam': array([26.59809744, 25.64596776]),
  'slicenum': array([10,  4]),
  'slicename': array(['410C', '404C'], dtype='<U4')},
 array([-503.39221343, -502.66650835]),
 array([-321.76840195, -317.87523125]))

In [7]:
alpha,beta,lam=values['alpha'],values['beta'],values['lam']

In [8]:
alpha,beta,lam

(array([-0.08228878, -0.0200367 ]),
 array([ 2.29611932, -1.64008523]),
 array([26.59809744, 25.64596776]))

Note that not every pixel on the detector actually maps to alpha,beta,lam since many pixels are between slices.  Therefore we have a way to 'trim' the inputs so that the returned values are only for such valid pixels.  Let's define an input array of pixels in which some map to slices and some do not.

In [9]:
x,y=[50,62,70,80,90],[500,510,520,10,950]

In [10]:
values=mrst.xytoabl(x,y,'1A',trim=1)

Note now that while we sent in five coordinates, only four got returned as one was trimmed.  The output values['x'] array is the trimmed version of the input x coordinate.

In [11]:
values

{'x': array([50, 70, 80, 90]),
 'y': array([500, 520,  10, 950]),
 'alpha': array([-0.33054596, -1.05170005,  1.47835852, -1.39725928]),
 'beta': array([ 1.77210144, -0.17721014, -0.17721014,  1.59489129]),
 'lam': array([5.32924427, 5.35736596, 4.89561251, 5.7004558 ]),
 'slicenum': array([21, 10, 10, 20]),
 'slicename': array(['121A', '110A', '110A', '120A'], dtype='<U4')}

We can convert alpha,beta to v2,v3 as well:

In [12]:
v2,v3=mrst.abtov2v3(values['alpha'],values['beta'],'1A')

In [13]:
v2,v3

(array([-503.95112523, -504.39842499, -501.88494031, -504.98817302]),
 array([-320.70383557, -318.66980031, -319.03983521, -320.36445205]))

In [14]:
# Test the Ch1A boresight location.  In FLT-3 this is -503.378025366985, -318.9991904123459
v2,v3=mrst.abtov2v3(0,0,'1A')
v2,v3

(-503.378025366985, -318.9991904123459)

### Now let's test that the distortion transforms for all 12 channels/subbands match reference positions correctly: ###

In [15]:
mrst.testtransform()

Testing channel 1A
Testing channel 1B
Testing channel 1C
Testing channel 2A
Testing channel 2B
Testing channel 2C
Testing channel 3A
Testing channel 3B
Testing channel 3C
Testing channel 4A
Testing channel 4B
Testing channel 4C


### Now we'll look at the implementation of the distortion solution in the JWST pipeline (mrs_pipetools) ###

In [16]:
from astropy.modeling import models
from asdf import AsdfFile
from jwst import datamodels
from jwst.assign_wcs import miri

In [17]:
import miricoord.mrs.mrs_pipetools as mrspt
mrspt.set_toolversion('flt4')

Quick test of using them directly

In [18]:
x,y=486,115
mrspt.xytoabl(x,y,'1A')

(0.21638418196526032, -1.77210143797, 4.971173485599659)

Point to a SHORT exposure reduced through spec2:

In [21]:
file=data_dir+'testing/jw02732004001_02101_00001_mirifushort_flt3_cal.fits'

Read the datamodel from the file and print some information about it

In [23]:
im = datamodels.ImageModel(file)

In [24]:
print(im.meta.wcs)

   From       Transform   
---------- ---------------
  detector detector_to_abl
alpha_beta    abl_to_v2v3l
      v2v3   CompoundModel
v2v3vacorr   CompoundModel
     world            None


These are the available frames for the distortion transforms:

In [25]:
print(im.meta.wcs.available_frames)

['detector', 'alpha_beta', 'v2v3', 'v2v3vacorr', 'world']


Define a point on the MRS and check that the v2,v3 is correct

In [26]:
alpha,beta,lam=0.0,0.0,5.0

In [27]:
v2,v3,ltemp=im.meta.wcs.transform("alpha_beta", "v2v3", alpha,beta,lam)

In [28]:
print(v2,v3)

-503.378025366985 -318.9991904123459


The V2,V3 location of the MRS 1A reference point should be -503.378025366985, -318.9991904123459

We can check the RA/DEC too:

In [29]:
ra, dec, ltemp = im.meta.wcs.transform("v2v3", "world", v2,v3,lam)

In [30]:
print(ra,dec)

339.01481919559063 33.97578326808422


### Now let's test that the distortion transforms for all 12 channels/subbands match reference positions correctly:  ###

In [31]:
mrspt.testtransform()

Testing channel 1A
Testing channel 1B
Testing channel 1C
Testing channel 2A
Testing channel 2B
Testing channel 2C
Testing channel 3A
Testing channel 3B
Testing channel 3C
Testing channel 4A
Testing channel 4B
Testing channel 4C
